USE workout_hub_2;

INSERT INTO exercises (name, description, muscle_group, difficulty, video_url, image_url) VALUES
('Classic Push-Ups', 'The fundamental chest movement for building upper body strength. Keep your core tight and elbows at a 45-degree angle.', 'Chest', 'Beginner', 'https://www.youtube.com/watch?v=IODxDxX7oi4', 'https://images.unsplash.com/photo-1571019614242-c5c5dee9f50b?auto=format&fit=crop&q=80&w=800'),
('Goblet Squats', 'Effective leg builder using a single weight. Keep your chest up and drive through your heels.', 'Legs', 'Intermediate', 'https://www.youtube.com/watch?v=MeIiGibT6X0', 'https://images.unsplash.com/photo-1605296867304-46d5465a13f1?auto=format&fit=crop&q=80&w=800'),
('Pull-Ups', 'The ultimate back and biceps builder. Grip the bar wider than shoulder-width and pull your chest to the bar.', 'Back', 'Advanced', 'https://www.youtube.com/watch?v=eGo4IYlbE5g', 'https://images.unsplash.com/photo-1598971639058-fab3c043bc6f?auto=format&fit=crop&q=80&w=800'),
('Dumbbell Shoulder Press', 'Build powerful shoulders. Sit upright and press the weights until arms are fully extended.', 'Shoulders', 'Intermediate', 'https://www.youtube.com/watch?v=qEwKCR5JCog', 'https://images.unsplash.com/photo-1541534741688-6078c64b5901?auto=format&fit=crop&q=80&w=800'),
('Plank', 'Core stability classic. Hold a straight line from head to heels.', 'Core', 'Beginner', 'https://www.youtube.com/watch?v=ASdvN_XEl_c', 'https://images.unsplash.com/photo-1566241142559-40e1bfc26cb4?auto=format&fit=crop&q=80&w=800'),
('Diamond Push-Ups', 'A variation of push-ups that targets the triceps and inner chest specifically. Form a diamond shape with your hands.', 'Chest', 'Intermediate', 'https://www.youtube.com/watch?v=J0DnG1_S92I', 'https://images.unsplash.com/photo-1599058917233-97f3b890aefd?auto=format&fit=crop&q=80&w=800'),
('Deadlifts', 'A powerhouse compound movement focusing on the entire posterior chain, including back and legs.', 'Back', 'Advanced', 'https://www.youtube.com/watch?v=op9kVnSso6Q', 'https://images.unsplash.com/photo-1517836357463-d25dfeac3438?auto=format&fit=crop&q=80&w=800'),
('Lunges', 'Excellent for lower body balance and strength. Step forward and lower your hips until both knees are bent at about a 90-degree angle.', 'Legs', 'Beginner', 'https://www.youtube.com/watch?v=QOVaHwm-Q6U', 'https://images.unsplash.com/photo-1434608519344-49d77a699e1d?auto=format&fit=crop&q=80&w=800'),
('Russian Twists', 'Target your obliques and improve rotational strength. Sit on the floor and twist your torso from side to side.', 'Core', 'Intermediate', 'https://www.youtube.com/watch?v=wkD8rjkodUI', 'https://images.unsplash.com/photo-1517838276556-782110144c8c?auto=format&fit=crop&q=80&w=800'),
('Lateral Raises', 'Isolate the lateral deltoids for broader shoulders. Use light weights and focus on form over load.', 'Shoulders', 'Beginner', 'https://www.youtube.com/watch?v=3VcKaXpzqRo', 'https://plus.unsplash.com/premium_photo-1664537158411-cf0660635436?auto=format&fit=crop&q=80&w=800'),
('Mountain Climbers', 'A high-intensity core and cardio movement. Bring knees to chest as fast as possible while maintaining a plank position.', 'Core', 'Intermediate', 'https://www.youtube.com/watch?v=zT-9L37ReNc', 'https://images.unsplash.com/photo-1598971639058-fab3c043bc6f?auto=format&fit=crop&q=80&w=800'),
('Bicep Curls', 'The classic isolation exercise for the biceps. Keep your elbows tucked and avoid swinging.', 'Arms', 'Beginner', 'https://www.youtube.com/watch?v=ykJmrZ5v0Oo', 'https://images.unsplash.com/photo-1581009146145-b5ef03a7403f?auto=format&fit=crop&q=80&w=800');
